Repository GSG-FC03/Todolist-Team1, pull requests merged in 2021-07, with the labels that each got.

#2 create read me file contains all details#1
  README.md
Labels: approved

#7 creating files structure
  css/home.css
  css/style.css
  html/home.html
  index.html
  script/main.js
Labels: approved

#9 5 create home page & style it
  assets/to-do.png
  assets/true.png
  css/home.css
  html/home.html
Labels: approved

#11 create task section
  css/home.css
  html/home.html
Labels: approved

#10 4 create welcompage
  css/style.css
  index.html
Labels: Done

#21 create popup form when click on add task button
  css/home.css
  html/home.html
  script/main.js
Labels: awaiting review

#22 make the function of add task button relates #17
  html/home.html
  script/main.js
Labels: awaiting review

#24 make form fields required and add id key for the task object
  html/home.html
  script/main.js
Labels: awaiting review

#25 19 render inputtasks in box task
  script/main.js
Labels: awaiting review

#26 add code that count the number of tasks done and un done Relates # 18
  html/home.html
  script/main.js
Labels: approved

#27 14 scripting edit save button
  css/home.css
  css/style.css
  html/home.html
  index.html
  script/main.js
Labels: awaiting review

#28 20 scripting checkbox
  script/main.js
Labels: approved

#29 Scripting delete button
  script/main.js
Labels: awaiting review

#32 fix checkbox
  css/home.css
  script/main.js
Labels: awaiting review

#34 33 update readme file
  README.md
  assets/design.jpg
Labels: awaiting review
